### ISSUE TITLE
使用COCO数据集训练后如何评测性能？

### ISSUE THREAD

**Issue by Mugealways** [YifanXu74/MQ-Det#16]
如题，首先感谢作者的工作，本人刚做这方面工作，有些东西还不是很懂请见谅。因为实验室服务器存储空间也不大，所以没法下载object365数据集提取vision_query并训练，所以我下了coco数据集提取了vision_query并训练。目前我想评测一下训练出来的模型性能如何，假如我想使用LVIS MiniVal或coco里的test数据集评测，请问我该执行什么命令呢？我也看了您在项目主页的那些指导评测的命令，有点猜测但不是很确定，所以想到直接问您确定一下比较靠谱。期待您的回复！

**Comment by Mugealways** [comment]
这样是否可以？
python -m torch.distributed.launch --nproc_per_node=1 \
tools/test_grounding_net.py \
--config-file configs/pretrain/mq-glip-t_coco.yaml \
--additional_model_config configs/vision_query_5shot/lvis_minival.yaml \
VISION_QUERY.QUERY_BANK_PATH MODEL/coco_query_5000_sel_tiny.pth \
MODEL.WEIGHT OUTPUT/MQ-GLIP-TINY-COCO/model_final.pth \
TEST.IMS_PER_BATCH 1

**Comment by Mugealways** [comment]
补充，运行上述命令报错：
RuntimeError: torch.cat(): expected a non-empty list of Tensors
猜想跟配置文件或者模型有关

**Comment by Mugealways** [comment]
@YifanXu74

**Comment by Mugealways** [comment]
后面将
--additional_model_config configs/vision_query_5shot/lvis_minival.yaml
换成了--additional_model_config configs/vision_query_5shot/coco.yaml就能跑通了

**Comment by YifanXu74** [comment]
嗯嗯，coco.yaml还没有经过测试，后面我会更新一版本详细的finetune指引文档哈
