### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Qia98** [YifanXu74/MQ-Det#17]
首先感谢作者的工作，作者的开创性图文并用的目标检测很吸引人，我正在尝试跑一个demo，然而在安装环境时我遇到了问题。
init.sh中前四行我都没有出现问题，我的环境是python==3.8.16, torch==2.0.1, GCC==5.2.0, CUDA==11.7.
`mkdir -p MODEL
mkdir -p DATASET
python -m pip install -r requirements.txt
python setup_glip.py build develop --user
python -m pip install -e .`
而在python -m pip install -e .时，出现了问题，查看报错发现是在编译groundingdino-new时出错

        ......running build_ext
        building 'groundingdino_new._C' extension
        /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.0) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
          warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
        Emitting ninja build file /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/build/temp.linux-x86_64-cpython-38/build.ninja...
        Compiling objects...
        Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
        [1/1]
        。。。DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++17
        FAILED: /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/build/temp.linux-x86_64-cpython-38/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/groundingdino_new/models/GroundingDINO/csrc_groundingdino/MsDeformAttn/ms_deform_attn_cuda.o

        /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++14 or later compatible compiler is required to use ATen.
         #error C++14 or later compatible compiler is required to use ATen.
          ^

        /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/zlchen/pkgs/gcc-5.2.0/gcc-bin/include/c++/5.2.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
         #error This file requires compiler and library support for the \
          ^

        /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++14 to compile PyTorch
         #error You need C++14 to compile PyTorch
          ^
       
        /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/zlchen/pkgs/gcc-5.2.0/gcc-bin/include/c++/5.2.0/bits/c++14_warning.h:32:2: error: #error This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
         #error This file requires compiler and library support for the forthcoming \
          ^
        
        /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/include/c10/util/variant.h:243:2: error: #error "MPark.Variant requires C++11 support."
         #error "MPark.Variant requires C++11 support."
          ^
        In file included from /usr/local/cuda-11.0/include/thrust/detail/config/config.h:27:0,
          。。。
        /usr/local/cuda-11.0/include/thrust/detail/config/cpp_dialect.h:104:13: warning: Thrust requires C++14. Please pass -std=c++14 to your compiler. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
           THRUST_COMPILER_DEPRECATION(C++14, pass -std=c++14 to your compiler);
                     ^
        ninja: build stopped: subcommand failed.
        Traceback (most recent call last):
          File "/home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
            subprocess.run(
          File "/home/anaconda3/envs/mqdet/lib/python3.8/subprocess.py", line 516, in run
            raise CalledProcessError(retcode, process.args,
        subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          。。。
          File "/home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
            raise RuntimeError(message) from e
        RuntimeError: Error compiling objects for extension
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
          ERROR: Can't roll back groundingdino-new; was not uninstalled
        error: subprocess-exited-with-error

      × python setup.py develop did not run successfully.
      │ exit code: 1
      ╰─> [153 lines of output]
          Building wheel groundingdino_new-0.1.0
          Compiling with CUDA
          running develop
          running egg_info
          writing groundingdino_new.egg-info/PKG-INFO
          writing dependency_links to groundingdino_new.egg-info/dependency_links.txt
          writing requirements to groundingdino_new.egg-info/requires.txt
          writing top-level names to groundingdino_new.egg-info/top_level.txt
          reading manifest file 'groundingdino_new.egg-info/SOURCES.txt'
          adding license file 'LICENSE'
          writing manifest file 'groundingdino_new.egg-info/SOURCES.txt'
          running build_ext
          building 'groundingdino_new._C' extension
          /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
            warnings.warn(
          /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
            warnings.warn(
          /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.0) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
            warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
          Emitting ninja build file /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/build/temp.linux-x86_64-cpython-38/build.ninja...
          Compiling objects...
          Allowing ninja to set a default number of workers... 
          。。。。
      ' -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 -std=c++17
          nvcc warning : The -std=c++17 flag is not supported with the configured host compiler. Flag will be ignored.
         
          /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++14 or later compatible compiler is required to use ATen.
           #error C++14 or later compatible compiler is required to use ATen.
            ^
          
          /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/zlchen/pkgs/gcc-5.2.0/gcc-bin/include/c++/5.2.0/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
           #error This file requires compiler and library support for the \
            ^
         
          /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++14 to compile PyTorch
           #error You need C++14 to compile PyTorch
            ^
         
          /mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/zlchen/pkgs/gcc-5.2.0/gcc-bin/include/c++/5.2.0/bits/c++14_warning.h:32:2: error: #error This file requires compiler and library support for the forthcoming ISO C++ 2014 standard. This support is currently experimental, and must be enabled with the -std=c++1y or -std=gnu++1y compiler options.
           #error This file requires compiler and library support for the forthcoming \
            ^
          
          /home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/include/c10/util/variant.h:243:2: error: #error "MPark.Variant requires C++11 support."
           #error "MPark.Variant requires C++11 support."
            ^
         
          /usr/local/cuda-11.0/include/thrust/detail/config/cpp_dialect.h:104:13: warning: Thrust requires C++14. Please pass -std=c++14 to your compiler. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
             THRUST_COMPILER_DEPRECATION(C++14, pass -std=c++14 to your compiler);
                       ^
          ninja: build stopped: subcommand failed.
          Traceback (most recent call last):
            File "/home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
              subprocess.run(
            File "/home/anaconda3/envs/mqdet/lib/python3.8/subprocess.py", line 516, in run
              raise CalledProcessError(retcode, process.args,
          subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
          
          The above exception was the direct cause of the following exception:
          
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            
            File "/home/anaconda3/envs/mqdet/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
              raise RuntimeError(message) from e
          RuntimeError: Error compiling objects for extension
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Qia98** [comment]
另外，编译groundingDino出错，而前面没有出错，是不是可以使用GLIP来跑demo？

**Comment by Qia98** [comment]
当我运行脚本时，`from maskrcnn_benchmark.utils.env import setup_environment  # noqa F401 isort:skip`会报错
        
```Traceback (most recent call last):
  File "test_grounding_net.py", line 13, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/maskrcnn_benchmark/data/build.py", line 12, in <module>
    from . import datasets as D
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/maskrcnn_benchmark/data/datasets/__init__.py", line 10, in <module>
    from .refexp import RefExpDataset
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/maskrcnn_benchmark/data/datasets/refexp.py", line 9, in <module>
    from maskrcnn_benchmark.layers.set_loss import generalized_box_iou
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/maskrcnn_benchmark/layers/__init__.py", line 10, in <module>
    from .nms import nms
  File "/mnt/dolphinfs/ssd_pool/docker/user/hadoop-seccv/nieweiqiang/video_cls_det/MQ-Det/maskrcnn_benchmark/layers/nms.py", line 2, in <module>
    from maskrcnn_benchmark import _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory```

**Comment by LiJunY** [comment]
@Qia98 遇到了同样的问题

**Comment by YifanXu74** [comment]
嗨，
感谢关注～我看到你在用较低版本的GCC，我之前在用低版本GCC时也遇到了类似的编译问题，可以试试以下的方法呢：
1. 升级GCC到8.0.0以上，论文中的实验环境时GCC==8.3.1
2. 如果只需要用GLIP来跑，需要把代码证groundingdino相关的部分注释掉，即：[[1](https://github.com/YifanXu74/MQ-Det/blob/611e176b016bf6777ccf21172a734b8bb0654f3a/maskrcnn_benchmark/modeling/detector/__init__.py#L2)]，[[2](https://github.com/YifanXu74/MQ-Det/blob/611e176b016bf6777ccf21172a734b8bb0654f3a/maskrcnn_benchmark/data/datasets/modulated_coco_new.py#L24-L25)]，[[3](https://github.com/YifanXu74/MQ-Det/blob/611e176b016bf6777ccf21172a734b8bb0654f3a/maskrcnn_benchmark/data/datasets/modulated_coco_new.py#L270-L275)]

如果还有问题，欢迎讨论哈
