### ISSUE TITLE
Question about Vision Query Extraction

### ISSUE THREAD

**Issue by Qia98** [YifanXu74/MQ-Det#28]
Which layers of the model are used for Vision Query Extraction? Is there a difference between using the official model and the model after Modulated Training or finetuning for Vision Query Extraction ?

**Comment by Qia98** [comment]
After debugging, I found that Vision Query Extraction only used the backbone, input_proj, pooler leayers of the model. Therefore, theoretically, Vision Query Extraction performed by these three models should result in the same .pth file. Am I correct?

**Comment by YifanXu74** [comment]
Yes. The vision queries are extracted via the backbone, which is frozen during pre-training. Therefore, if the models share the same backbone weight, their extracted vision queries should be the same. But clearly GLIP-L, GLIP-T, and GroundingDINO do not share the same backbone weight, so their extracted .pth files are different.
