### ISSUE TITLE
Finetune on custom dataset with and without vision query

### ISSUE THREAD

**Issue by HaisongDing** [YifanXu74/MQ-Det#30]
How should I set the "SOLVER.TUNING_HIGHLEVEL_OVERRIDE" value if I want to finetune the pre-trained model with vision query? 

And when I want to disable vision query (like original GLIP), how should I set the value?

**Comment by YifanXu74** [comment]
Hi,

To finetune the pre-trained model with vision query, you can try setting "SOLVER.TUNING_HIGHLEVEL_OVERRIDE" to "full" if using the ``finetune.py`` script. 
To disable vision query, just set "VISION_QUERY.ENABLED" to False.

**Comment by HaisongDing** [comment]
Thanks.

**Comment by HaisongDing** [comment]
Follow up question, when I use "vision_query_v3" and set
```
Backbone Freeze: True
FPN Freeze: True
RPN Freeze: True
Linear Probe: False
Language Freeze: False
Linear Layer (True Prmopt Tuning): True
High Level Override: vision_query_v3
``` 
The language backbone part is also frozen:
```
module.language_backbone.body.model.embeddings.word_embeddings.weight  : Frozen
module.language_backbone.body.model.embeddings.position_embeddings.weight  : Frozen
module.language_backbone.body.model.embeddings.token_type_embeddings.weight  : Frozen
module.language_backbone.body.model.embeddings.LayerNorm.weight  : Frozen
module.language_backbone.body.model.embeddings.LayerNorm.bias  : Frozen
...
module.language_backbone.body.model.pre_select.layers.1.image_condition.to_out.weight  : Not Frozen
module.language_backbone.body.model.pre_select.layers.1.ff.norm.weight  : Not Frozen
module.language_backbone.body.model.pre_select.layers.1.ff.norm.bias  : Not Frozen
module.language_backbone.body.model.pre_select.layers.1.ff.linear1.weight  : Not Frozen
module.language_backbone.body.model.pre_select.layers.1.ff.linear2.weight  : Not Frozen
module.language_backbone.body.model.pre_select.layers.1.res_mapping.weight  : Not Frozen
```
This is un-expected. How should I set the value if I want to finetune the MQ-Det's full language backbone and vision query parts?

**Comment by YifanXu74** [comment]
I guess this is because the fine-tuning script will automatically freeze the language backbone once "vision_query" is in SOLVER.TUNING_HIGHLEVEL_OVERRIDE (see [here](https://github.com/YifanXu74/MQ-Det/blob/611e176b016bf6777ccf21172a734b8bb0654f3a/tools/finetune.py#L184-L188)). So, one straightforward solution is to modify the name [here](https://github.com/YifanXu74/MQ-Det/blob/611e176b016bf6777ccf21172a734b8bb0654f3a/tools/finetune.py#L369C10-L369C10) to make sure "vision_query" is not in the name.

**Comment by YifanXu74** [comment]
Thanks! Combining MQ-Det with DINOv sounds very interesting.
