### ISSUE TITLE
GCP相关代码在哪个位置呢？

### ISSUE THREAD

**Issue by Mugealways** [YifanXu74/MQ-Det#34]
首先感谢作者的工作！由于本人偏小白，最近想看论文中描述的GCP模块的代码来加深理解，特别是其中target img 和vision query之间cross attention以及Conditional Gate的代码；但是受限于自身水平没有找到这些代码所处的位置。劳烦作者指点一二，谢谢！

**Comment by YifanXu74** [comment]
哈喽！

GCP的实现在这个文件内，见[这里](https://github.com/YifanXu74/MQ-Det/blob/5c4a739a79b04e2ba6bf6a42697bbc6bd3b67e79/maskrcnn_benchmark/modeling/language_backbone/modeling_bert_new.py#L250C2-L250C2)

**Comment by Mugealways** [comment]
谢谢！努力在您回复之前自己看懂了哈哈😄

**Comment by lc783** [comment]
你好，我似没有找到target img 和vision query之间cross attention，请问这部分代码你知道在哪吗

**Comment by Mugealways** [comment]
> 你好，我似没有找到target img 和vision query之间cross attention，请问这部分代码你知道在哪吗

应该是在preselectmodule这块
