### ISSUE TITLE
GCP中的QKV的维度

### ISSUE THREAD

**Issue by Mugealways** [YifanXu74/MQ-Det#40]
作者你好，关于gcp中的QKV的维度我有一点问题，可能问题有点小白，请见谅。figure1中我看2个cross attention 输入的Vision Query Features是多个的，但是经过2个cross attention之后，输出的那个KV（Class-wise Cross Attn左边）怎么变成了2个呢？我对cross attention的理解是输出的维度不应该是和Q的维度是一样的么，那么输出的KV应当是不止2个。如果我的理解有误，麻烦作者指点一下我，期待您的回复，谢谢！

**Comment by YifanXu74** [comment]
嗨！

Fig 1只是示意哈，实际经过2个cross attention后Query Features数量还是没变的，只是图中的KV中间没地方画省略号了

**Comment by Swaggeraqua** [comment]
> 嗨！
> 
> Fig 1只是示意哈，实际经过2个cross attention后Query Features数量还是没变的，只是图中的KV中间没地方画省略号了

作者你好，
请问何时有空能更新inference 检测单张图片

**Comment by Swaggeraqua** [comment]
@YifanXu74 
作者你好，
请问何时有空能更新inference 检测单张图片

**Comment by YifanXu74** [comment]
@Swaggeraqua 过段时间吧，最近排期比较满 :(

**Comment by Swaggeraqua** [comment]
@YifanXu74 好的，非常感谢

**Comment by Mugealways** [comment]
感谢您的回复！
