### ISSUE TITLE
关于config文件的疑问

### ISSUE THREAD

**Issue by Real-UtopiaNo** [YifanXu74/MQ-Det#47]
论文中提到文本编码器和视觉编码器是冻结的，但是config文件中**LANGUAGE_BACKBONE.FREEZE**和**BACKBONE.FREEZE_CONV_BODY_AT**这两个参数却分别设置为**FALSE**和**-1**

**Comment by YifanXu74** [comment]
嗨，因为LANGUAGE_BACKBONE.FREEZE控制的是整个language backbone的参数，如果设置为True，则会连GCP一起冻结住。BACKBONE.FREEZE_CONV_BODY_AT 在 MODEL.BACKBONE.FREEZE为True的情况下是没用的。

各种参数实际的冻结情况由SOLVER.TUNING_HIGHLEVEL_OVERRIDE控制，见[这里](https://github.com/YifanXu74/MQ-Det/blob/6ad1be63cafa84bc3e957f3764ab435dd0d51061/tools/train_net.py#L42-L50)和[这里](https://github.com/YifanXu74/MQ-Det/blob/6ad1be63cafa84bc3e957f3764ab435dd0d51061/tools/train_net.py#L73-L77)。

**Comment by Real-UtopiaNo** [comment]
> 嗨，因为LANGUAGE_BACKBONE.FREEZE控制的是整个language backbone的参数，如果设置为True，则会连GCP一起冻结住。BACKBONE.FREEZE_CONV_BODY_AT 在 MODEL.BACKBONE.FREEZE为True的情况下是没用的。
> 
> 各种参数实际的冻结情况由SOLVER.TUNING_HIGHLEVEL_OVERRIDE控制，见[这里](https://github.com/YifanXu74/MQ-Det/blob/6ad1be63cafa84bc3e957f3764ab435dd0d51061/tools/train_net.py#L42-L50)和[这里](https://github.com/YifanXu74/MQ-Det/blob/6ad1be63cafa84bc3e957f3764ab435dd0d51061/tools/train_net.py#L73-L77)。

我明白了，感谢回复！
