### ISSUE TITLE
怎么增加评估时的TEST.IMS_PER_BATCH而不报错？

### ISSUE THREAD

**Issue by Mugealways** [YifanXu74/MQ-Det#54]
如题，我的实验环境只有一张4090，我在评估val 1.0时发现TEST.IMS_PER_BATCH=1时预估时间要34个小时了，但是我看显卡占用只有5000多MiB。因此我想增加TEST.IMS_PER_BATCH以加快评估速度，但是报错：

  File "/home/ecust/ltt/MQ-Det/maskrcnn_benchmark/modeling/detector/generalized_vl_rcnn_new.py", line 355, in forward
    assert images.tensors.shape[0]==1 # TODO: Only query batch size = 1 for test
AssertionError

请问有什么解决的办法吗？

**Comment by YifanXu74** [comment]
是的，目前只支持TEST.IMS_PER_BATCH=1。理论上是可以进行并行eval的，可以把报错的这一行注释后自行调试一下哈

**Comment by Mugealways** [comment]
好的，感谢您的回复！

**Comment by Polarisamoon** [comment]
您好，请问你解决了吗？我也觉得评估太慢了
