### ISSUE TITLE
论文标题中 "in the wild" 是什么意思？

### ISSUE THREAD

**Issue by auniquesun** [YifanXu74/MQ-Det#7]
物体检测比较清楚，但我一直不太明白结合 “in the wild” 是什么意思，您能否根据文章解释一下？谢谢。

**Comment by YifanXu74** [comment]
@auniquesun Thank you for your interest in our work. The key goal of multi-modal queried object detection is "open-vocabulary" and "various granularity", where the former stands for a wide range of category concepts (brought by language) and the latter represents for deep granularity (brought by images) of one superclass, e.g., "clownfish" and "stingray" in a superclass "fish". "In the wild" can indicate both "wide vocabulary" and "granularity", while open-world or open-set only represents for "wide vocabulary".

**Comment by auniquesun** [comment]
Thanks, I got it.
