### ISSUE TITLE
problems about pretrain dataset

### ISSUE THREAD

**Issue by Azong-HQU** [YifanXu74/MQ-Det#9]
作者您好，我对您的工作非常感兴趣，可惜我没有object365数据集，无法顺利debug代码，请问我能否用其他数据集代替呢？

**Comment by YifanXu74** [comment]
Hi @Azong-HQU ,

I have updated an instruction of modulated training on customized datasets. You can use the COCO example in the instruction for debug. Please refer to [CUSTOMIZED_PRETRAIN.md](https://github.com/YifanXu74/MQ-Det/blob/main/CUSTOMIZED_PRETRAIN.md).

**Comment by Azong-HQU** [comment]
Thanks !

**Comment by Azong-HQU** [comment]
作者您好，我按照您的意见进行debug代码，配置文件使用mq-glip-t_coco.yaml，数据使用COCO，但我貌似没看到（执行）文章中关于[**Vision conditioned masked language prediction**]这一部分的代码？请问作者方便提示我一下吗？万分感激！！！
![image](https://github.com/YifanXu74/MQ-Det/assets/25705905/b99727ab-4f50-4d4a-a076-90d0949596ba)

**Comment by YifanXu74** [comment]
@Azong-HQU The code of vision conditioned masked language prediction can be found [here](https://github.com/YifanXu74/MQ-Det/blob/5c4a739a79b04e2ba6bf6a42697bbc6bd3b67e79/maskrcnn_benchmark/modeling/detector/generalized_vl_rcnn_new.py#L397-L407).

**Comment by YifanXu74** [comment]
There is a bug in step 3 (extract vision query) of [CUSTOMIZED_PRETRAIN.md](https://github.com/YifanXu74/MQ-Det/blob/main/CUSTOMIZED_PRETRAIN.md), which should specify ``VISION_QUERY.QUERY_BANK_PATH ""``. I have fixed it in the latest version.

**Comment by Azong-HQU** [comment]
Thanks!
